DATASETS_PATH = './datasets'
PLAYER_FILENAME = 'player_data.csv'
PLAYER_WITH_GW_FILENAME = 'player_with_GW_data.csv'
PLAYER_PROCESSED_FILENAME = 'player_data_processed.csv'
TEAM_FILENAME = 'team_data.csv'
FIXTURE_FILENAME = 'fixture_data.csv'